# Generated by Django 2.2 on 2021-02-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Image',
        ),
        migrations.AddField(
            model_name='post',
            name='Description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
