# Generated by Django 2.2 on 2021-02-22 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210222_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='messages',
        ),
    ]
